# alerts/alerter.py
# ─────────────────────────────────────────────────
# Phase 4: Alert system.
# Sends email alerts when strong signals fire.
# Supports: STRONG_BUY, CLUSTER_BUY, REVERSION
#
# Setup: add your email config to config/settings.py
# ─────────────────────────────────────────────────

import smtplib
import logging
from email.mime.text      import MIMEText
from email.mime.multipart import MIMEMultipart
from datetime             import datetime

logger = logging.getLogger(__name__)


def send_email_alert(
    subject:    str,
    body_html:  str,
    smtp_host:  str,
    smtp_port:  int,
    smtp_user:  str,
    smtp_pass:  str,
    from_addr:  str,
    to_addrs:   list[str],
) -> bool:
    """Send an HTML email alert. Returns True on success."""
    try:
        msg = MIMEMultipart("alternative")
        msg["Subject"] = subject
        msg["From"]    = from_addr
        msg["To"]      = ", ".join(to_addrs)

        msg.attach(MIMEText(body_html, "html"))

        with smtplib.SMTP_SSL(smtp_host, smtp_port) as server:
            server.login(smtp_user, smtp_pass)
            server.sendmail(from_addr, to_addrs, msg.as_string())

        logger.info(f"Alert sent: {subject} → {to_addrs}")
        return True

    except Exception as e:
        logger.error(f"Alert failed: {e}")
        return False


def build_signal_alert_html(signals: list[dict], scan_results: dict) -> str:
    """Build HTML email body for signal alerts."""
    now = datetime.now().strftime("%Y-%m-%d %H:%M")

    # Signal table rows
    signal_rows = ""
    for s in signals[:20]:
        colour = "#00c853" if s.get("rating") in ("STRONG_BUY","BUY") else "#ff6f00"
        signal_rows += f"""
        <tr>
            <td style="padding:8px;font-weight:bold;color:#00bcd4">{s.get('ticker','')}</td>
            <td style="padding:8px;color:{colour};font-weight:bold">{s.get('rating','')}</td>
            <td style="padding:8px;text-align:right">{s.get('composite_score','')}</td>
            <td style="padding:8px;text-align:right">{s.get('momentum_score','')}</td>
            <td style="padding:8px;text-align:right">{s.get('quality_score','')}</td>
            <td style="padding:8px;text-align:right">{s.get('insider_score','')}</td>
            <td style="padding:8px;font-size:11px">{(s.get('flags','') or '').replace('|','  ')[:60]}</td>
        </tr>"""

    # Cluster signal rows
    cluster_rows = ""
    for scan_name, items in scan_results.items():
        for item in items[:5]:
            cluster_rows += f"""
            <tr>
                <td style="padding:8px;font-weight:bold;color:#00bcd4">{item.get('ticker','')}</td>
                <td style="padding:8px;color:#ff9800">{scan_name.replace('_',' ').title()}</td>
                <td style="padding:8px">{item.get('company','')}</td>
                <td style="padding:8px;font-size:11px">{' | '.join(item.get('reasons',[])[:2])}</td>
            </tr>"""

    html = f"""
    <!DOCTYPE html>
    <html>
    <head>
        <style>
            body {{ font-family: Arial, sans-serif; background: #1a1a2e; color: #e0e0e0; margin: 0; padding: 20px; }}
            .container {{ max-width: 900px; margin: 0 auto; }}
            h1 {{ color: #00bcd4; border-bottom: 2px solid #00bcd4; padding-bottom: 10px; }}
            h2 {{ color: #90caf9; margin-top: 30px; }}
            table {{ width: 100%; border-collapse: collapse; margin: 15px 0; }}
            th {{ background: #0d47a1; color: white; padding: 10px; text-align: left; }}
            tr:nth-child(even) {{ background: #1e1e3a; }}
            tr:nth-child(odd)  {{ background: #16213e; }}
            .footer {{ color: #666; font-size: 12px; margin-top: 30px; border-top: 1px solid #333; padding-top: 10px; }}
        </style>
    </head>
    <body>
    <div class="container">
        <h1>📈 Trading System Alert — {now}</h1>

        <h2>Top Signals</h2>
        <table>
            <tr>
                <th>Ticker</th><th>Rating</th><th>Score</th>
                <th>Momentum</th><th>Quality</th><th>Insider</th><th>Flags</th>
            </tr>
            {signal_rows}
        </table>

        <h2>Confluence Scans</h2>
        <table>
            <tr><th>Ticker</th><th>Scan</th><th>Company</th><th>Reasons</th></tr>
            {cluster_rows if cluster_rows else '<tr><td colspan="4" style="padding:8px;color:#666">No confluence hits</td></tr>'}
        </table>

        <div class="footer">
            Generated by Trading System | Data from FinViz<br>
            This is not financial advice. Always do your own research.
        </div>
    </div>
    </body>
    </html>
    """
    return html


def build_cluster_alert_html(cluster_signals: list[dict]) -> str:
    """Build HTML email for insider cluster signals specifically."""
    now = datetime.now().strftime("%Y-%m-%d %H:%M")

    rows = ""
    for s in cluster_signals:
        is_buy = "BUY" in (s.get("signal_type") or "")
        colour = "#00c853" if is_buy else "#f44336"
        value  = f"${s.get('total_value',0):,.0f}" if s.get("total_value") else "-"
        rows += f"""
        <tr>
            <td style="padding:8px;font-weight:bold;color:#00bcd4">{s.get('ticker','')}</td>
            <td style="padding:8px;color:{colour};font-weight:bold">{s.get('signal_type','')}</td>
            <td style="padding:8px;text-align:right">{s.get('insider_count','')}</td>
            <td style="padding:8px;text-align:right">{value}</td>
            <td style="padding:8px;font-size:11px">{(s.get('notes','') or '')[:80]}</td>
        </tr>"""

    buy_count  = sum(1 for s in cluster_signals if "BUY"  in (s.get("signal_type") or ""))
    sell_count = sum(1 for s in cluster_signals if "SELL" in (s.get("signal_type") or ""))

    html = f"""
    <!DOCTYPE html>
    <html>
    <head>
        <style>
            body {{ font-family: Arial, sans-serif; background: #1a1a2e; color: #e0e0e0; margin: 0; padding: 20px; }}
            .container {{ max-width: 800px; margin: 0 auto; }}
            h1 {{ color: #00bcd4; border-bottom: 2px solid #00bcd4; padding-bottom: 10px; }}
            table {{ width: 100%; border-collapse: collapse; margin: 15px 0; }}
            th {{ background: #0d47a1; color: white; padding: 10px; text-align: left; }}
            tr:nth-child(even) {{ background: #1e1e3a; }}
            tr:nth-child(odd)  {{ background: #16213e; }}
            .summary {{ background: #0d1b2a; padding: 15px; border-radius: 8px; margin: 15px 0; }}
            .footer {{ color: #666; font-size: 12px; margin-top: 30px; }}
        </style>
    </head>
    <body>
    <div class="container">
        <h1>🔍 Insider Cluster Alert — {now}</h1>
        <div class="summary">
            <strong style="color:#00c853">{buy_count} CLUSTER BUY signals</strong> &nbsp;|&nbsp;
            <strong style="color:#f44336">{sell_count} CLUSTER SELL signals</strong>
        </div>
        <table>
            <tr><th>Ticker</th><th>Signal</th><th>Insiders</th><th>Total Value</th><th>Who</th></tr>
            {rows}
        </table>
        <div class="footer">
            Trading System | Not financial advice.
        </div>
    </div>
    </body>
    </html>
    """
    return html


class AlertManager:
    """
    Manages alert sending with deduplication.
    Tracks which alerts have been sent to avoid spam.
    """

    def __init__(self, db_path: str, config: dict):
        self.db_path = db_path
        self.config  = config
        self._ensure_alert_log_table()

    def _ensure_alert_log_table(self):
        import sqlite3
        conn = sqlite3.connect(self.db_path)
        conn.execute("""
            CREATE TABLE IF NOT EXISTS alert_log (
                id          INTEGER PRIMARY KEY AUTOINCREMENT,
                sent_at     TEXT,
                alert_type  TEXT,
                subject     TEXT,
                recipients  TEXT,
                success     INTEGER
            )
        """)
        conn.commit()
        conn.close()

    def _log_alert(self, alert_type: str, subject: str, success: bool):
        import sqlite3
        conn = sqlite3.connect(self.db_path)
        conn.execute("""
            INSERT INTO alert_log (sent_at, alert_type, subject, recipients, success)
            VALUES (?, ?, ?, ?, ?)
        """, (
            datetime.now().isoformat(),
            alert_type, subject,
            ",".join(self.config.get("to_addrs", [])),
            int(success)
        ))
        conn.commit()
        conn.close()

    def send_signal_alert(self, signals: list[dict], scan_results: dict) -> bool:
        if not signals:
            return False

        top_rating = signals[0].get("rating", "BUY")
        count      = len(signals)
        subject    = f"📈 Trading Alert: {count} {top_rating} signals detected"
        body       = build_signal_alert_html(signals, scan_results)

        success = send_email_alert(
            subject   = subject,
            body_html = body,
            **{k: self.config[k] for k in
               ["smtp_host","smtp_port","smtp_user","smtp_pass","from_addr","to_addrs"]}
        )
        self._log_alert("SIGNAL", subject, success)
        return success

    def send_cluster_alert(self, cluster_signals: list[dict]) -> bool:
        if not cluster_signals:
            return False

        buy_count = sum(1 for s in cluster_signals if "BUY" in (s.get("signal_type") or ""))
        subject   = f"🔍 Insider Alert: {buy_count} cluster buys detected"
        body      = build_cluster_alert_html(cluster_signals)

        success = send_email_alert(
            subject   = subject,
            body_html = body,
            **{k: self.config[k] for k in
               ["smtp_host","smtp_port","smtp_user","smtp_pass","from_addr","to_addrs"]}
        )
        self._log_alert("CLUSTER", subject, success)
        return success
